#if !canImport(ObjectiveC)
import XCTest

extension EnvironmentConfigTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EnvironmentConfigTests = [
        ("testFatalMissing", testFatalMissing),
        ("testImplicitKeys", testImplicitKeys),
        ("testOptionals", testOptionals),
        ("testReadEnv", testReadEnv),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(EnvironmentConfigTests.__allTests__EnvironmentConfigTests),
    ]
}
#endif
